curl -XPOST 'http://localhost:9200/_bulk?pretty=true' \
-H 'Content-type: application/x-ndjson' \
-d '{ "delete" : { "_index" : "movies-v1", "_id" : "1" } }
{ "index" : { "_index" : "movies-v1", "_id" : "1" } }
{"name": "The Lord of the Rings: The Fellowship of the Ring", "description": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", "cast": ["Alan Howard", "Noel Appleby", "Sean Astin", "Sala Baker", "Sean Bean", "Cate Blanchett", "Orlando Bloom", "Billy Boyd"], "duration_minutes": 179, "genre": ["Action", "Adventure", "Drama"], "language": ["English"], "rating": 8.8, "release_data": "19-12-2001", "created_at": "04-04-2020 11:31:03", "updated_at": "04-04-2020 11:31:03"}
{ "index" : { "_index" : "movies-v1", "_id" : "2" } }
{"name": "The Shawshank Redemption", "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", "cast": ["Tim Robbins", "Morgan Freeman", "Bob Gunton"], "duration_minutes": 142, "genre": ["Drama"], "language": ["English"], "rating": 9.3, "release_data": "17-02-1995", "created_at": "05-04-2020 13:31:03", "updated_at": "05-04-2020 13:31:03"}
{ "index" : { "_index" : "movies-v1", "_id" : "3" } }
{"name": "The Terminal", "description": "An Eastern European tourist unexpectedly finds himself stranded in JFK airport, and must take up temporary residence there.", "cast": ["Tom Hanks", "Catherine Zeta-Jones", "Chi McBride"], "duration_minutes": 128, "genre": ["Comedy", "Drama", "Romance"], "language": ["English"], "rating": 7.4, "release_data": "03-09-2004", "created_at": "05-04-2020 13:35:01", "updated_at": "05-04-2020 13:35:01"}
{ "index" : { "_index" : "movies-v1", "_id" : "4" } }
{"name": "The Dark Knight", "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", "cast": ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], "duration_minutes": 152, "genre": ["Action", "Drama", "Crime"], "language": ["English"], "rating": 9.0, "release_data": "24-07-2008", "created_at": "05-04-2020 13:41:12", "updated_at": "05-04-2020 13:41:12"}
{ "index" : { "_index" : "movies-v3", "_id" : "5" } }
{"name": "Batman Begins", "description": "After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.", "cast": ["Christian Bale", "Michael Caine", "Ken Watanabe"], "duration_minutes": 140, "genre": ["Action", "Adventure"], "language": ["English"], "rating": 8.2, "release_data": "16-06-2005", "created_at": "05-04-2020 13:43:02", "updated_at": "05-04-2020 13:43:02"}
{ "index" : { "_index" : "movies-v3", "_id" : "6" } }
{"name": "The Matrix", "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Christian Scotts"], "duration_minutes": 136, "genre": ["Action", "Sci-Fi"], "language": ["English"], "rating": 8.7, "release_data": "11-06-1999", "created_at": "05-04-2020 13:48:02", "updated_at": "05-04-2020 13:48:02"}
{ "index" : { "_index" : "movies-v3", "_id" : "7" } }
{"name": "Batman v Superman: Dawn of Justice", "description": "Fearing that the actions of Superman are left unchecked, Batman takes on the Man of Steel, while the world wrestles with what kind of a hero it really needs.", "cast": [ "Ben Affleck", "Henry Cavill", "Amy Adams"], "duration_minutes": 151, "genre": ["Action", "Adventure", "Sci-Fi"], "language": ["English"], "rating": 6.5, "release_data": "25-03-2016", "created_at": "05-04-2020 17:42:03", "updated_at": "05-04-2020 17:42:03"}
'
